os:
  - linux

dist:
  - bionic
  - xenial
  - trusty

language:
  - C

script:
  - make -j 2 DESTDIR="$PWD/_i"
  - make -j 2 DESTDIR="$PWD/_i" install
  - ./beep --version > beep-usage.from--version
  # - grep "$(date +%Y)" beep-usage.from--version
  - cat beep-usage.from--version
  - ./beep --help > beep-usage.from--help
  - diff -u beep-usage.txt beep-usage.from--help
  - ls -l
  - ls -lR _i/
